library(shiny)
library(shinythemes)
library(here)
library(tidyverse)
library(sf)
library(tmap)
library(rmapshaper)
library(leaflet)
library(shapefiles)
library(rgdal)

source(here("r_scripts/life_expectancy.R"))
source(here("r_scripts/priority_2_ p1_bmi_script.R"))
source(here("r_scripts/bmi.R"))
source(here("r_scripts/exercise.R"))
source(here("r_scripts/map_asthma.R"))
source(here("r_scripts/priority_3_graph.R"))
source(here("r_scripts/priority_4_graph.R"))
